const domain = "nettasec.com";

const SEO = {
  layoutTitle: "%s | NettaSec Solutions",
  title: "NettaSec Solutions",
  domain,
  publishDomain: `https://${domain}`,
  themeColor: "#a44246",
  keywords: [
    "NettaSec Solutions",
    "Nettasec şirketi",
    "alper karakoyun",
    ".kwa",
    "kwasec",
    "kwa0x2",
    "kwa",
    "blog",
    "software",
    "yazilim",
    "web",
    "tekirdağ siber güvenlik",
    "tekirdağ siber güvenlik şirketi",
    "tekirdağ yazılım şirketi",
    "tekirdağ çorlu yazılım şirketi",
    "tekirdağ çorlu siber güvenlik",
    "tekirdağ çorlu siber güvenlik şirketi",
    "çorlu yazılım şirketi",
    "çorlu siber güvenlik",
    "çorlu siber güvenlik şirketi",
    "ingiltere siber güvenlik",
    "ingiltere siber güvenlik şirketi",
    "ingiltere yazılım şirketi",
    "londra siber güvenlik",
    "londra siber güvenlik şirketi",
    "londra yazılım şirketi",
    "UK cyber security",
    "UK cyber security company",
    "UK software company",
    "London cyber security",
    "London cyber security company",
    "London software company",
    "programming",
    "backend",
    "back end",
    "go",
    "go lang",
    "golang",
    "web tabanlı uygulama geliştirme",
    "siber güvenlik",
    "cyber security",
    "cybersecurity",
    "cyber security consulting",
    "cybersecurity consulting",
    "backend development",
    "backend geliştirme",
    "cybersecurity solutions",
    "pen test",
    "pentest",
    "penetration testing",
    "waf security services",
    "firewall security services",
    "waf security",
    "yazılım güvenliği",
    "software security",
    "penetrasyon testi hizmetleri",
    "penetrasyon testi",
    "waf",
    "web application firewall",
    "firewall",
    "ethical hacking",
    "siber güvenlik çözümleri",
    "siber güvenlik hizmetleri",
    "güvenlik hizmetleri",
    "siber güvenlik uzmanı",
    "kaliteli hizmet",
    "çözüm odaklı",
    "teknoloji",
    "technology",
    "software solutions",
    "yazılım çözümleri",
    "entegre çözümler",
    "üst düzey hizmet",
  ],
  description:
    "NettaSec Solutions is a technology company based in Turkey and the United Kingdom, providing services in areas such as cybersecurity, cloud computing, penetration testing, WAF security services, and backend development. We offer innovative solutions in cybersecurity consulting, security services, and software development, ensuring secure and reliable digital environments for our clients. With a comprehensive approach to meeting businesses' security needs and protecting their digital assets, NettaSec Solutions has strong technical expertise and experience to guide clients safely through their digital transformation.",
};

export const CONFIG = {
  GA_TRACKING_ID: "G-WXQDEQ6DDX",
  SEO,
};